#
#  _   _ _______        _____  ____  _     _____ _____ ____   __     ______
# | | | | ____\ \      / / _ \/ ___|| |   | ____| ____|  _ \  \ \   / /___ \
# | |_| |  _|  \ \ /\ / / | | \___ \| |   |  _| |  _| | |_) |  \ \ / /  __) |
# |  _  | |___  \ V  V /| |_| |___) | |___| |___| |___|  __/    \ V /  / __/
# |_| |_|_____|  \_/\_/  \___/|____/|_____|_____|_____|_|        \_/  |_____|
#

# Here you can customize the plugin configurations

# You can choose what language that plugin should use
# Options: en-US (English), fil-PH (Filipino)
# Note: After changing this, please delete 'lang.yml' and do /hs reload
# Default: en-US
language: "en-US"

# You can choose if you want to get notify if newer version is available
# Default: true
check_updates: true

# You can choose whether essentials affects the plugin or not.
# Essentials are used for the afk and vanish bypass.
# true  - Enable Essentials
# false - Disable Essentials
# Default: true
essentials_support: true

# You can choose whether players that execute /lay will count as sleepers or not.
# true  - Enable GSit
# false - Disable GSit
# Default: true
gsit_support: true