
#  _    _ ________          ______   _____ _      ______ ______ _____   __      ____
# | |  | |  ____\ \        / / __ \ / ____| |    |  ____|  ____|  __ \  \ \    / /_ |
# | |__| | |__   \ \  /\  / / |  | | (___ | |    | |__  | |__  | |__) |  \ \  / / | |
# |  __  |  __|   \ \/  \/ /| |  | |\___ \| |    |  __| |  __| |  ___/    \ \/ /  | |
# | |  | | |____   \  /\  / | |__| |____) | |____| |____| |____| |         \  /   | |
# |_|  |_|______|   \/  \/   \____/|_____/|______|______|______|_|          \/    |_|

# Choose if the multiplayer sleep is enabled
# true    - to enable the multiplayer sleep
# false   - to disable the multiplayer sleep
# Default: false
enable: false

# Choose how many percentage of players are needed to sleep
# eg. (percentage: 20 -> players: 10 -> needed to sleep to skip the night/storm: 2 players)
# Default: 100
percentage: 100

# The time in seconds that players need to wait before they can enter the bed again after leaving it
# Default: 10
bed_enter_delay: 10

# The duration (in seconds) of the day
# This allows you to sped up or slow down the day
# Default: 700
day_length: 700

# The duration (in seconds) of the night when not skipping
# This allows you to sped up or slow down the night
# Default: 500
night_length: 500

# The duration (in seconds) of the night when skipping
# Set this to 0 to skip the night instantly
# Default: 4
night_skip_length: 4

# Choose if you want to ignore afk players to be able to skip the night
# This is mostly used when player is afk but the number of sleepers is not enough
# If player is not moving more than 3 minutes will be considered as afk player
# true    - ignoring to count afk players in number of sleepers
# false   - afk players will not ignore in counting number of sleepers
# Default: false
ignore_afk_players: false

# Choose if you want to ignore vanished players to be able to skip the night
# true    - ignoring to count vanished players in number of sleepers
# false   - vanished players will not ignore in counting number of players
# Default: true
# Note: This is only work when you have Essentials plugin
ignore_vanish_players: true